---
title: "Figure 1 processing script"
author: "Hyunwoo Cho"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=F}
knitr::opts_chunk$set(
  warning=F,
  message=F,
  fig.width=7, fig.height=7,
  echo=T
)
```

```{r load-library-1}
library(data.table)
library(openxlsx)
library(pheatmap)
library(magrittr)
```

Figure 1B

The panel is based on the matrix of Pearson correlation of the median-normalized CRISPR screen counts.

```{r load-fig-1b-1, echo=F}
large.screen.data = list(
  D16=read.xlsx("internal-data/220929 large pool gRNA raw and processed.xlsx", sheet=1, rows=1:539),
  D25m=read.xlsx("internal-data/220929 large pool gRNA raw and processed.xlsx", sheet=2, rows=1:539),
  D25p=read.xlsx("internal-data/220929 large pool gRNA raw and processed.xlsx", sheet=3, rows=1:539),
  D25g=read.xlsx("internal-data/220929 large pool gRNA raw and processed.xlsx", sheet=4, rows=1:539)
)
```

```{r fig-1b-1}
# large.screen.data = list(
#   D16=fread("column 1.txt"),
#   D25m=fread("column 2.txt"),
#   D25p=fread("column 3.txt"),
#   D25g=fread("column 4.txt")
# )

all.equal(large.screen.data$D16$NAME, large.screen.data$D25m$NAME)
# [1] TRUE
all.equal(large.screen.data$D16$NAME, large.screen.data$D25p$NAME)
# [1] TRUE
all.equal(large.screen.data$D16$NAME, large.screen.data$D25g$NAME)
# [1] TRUE
setdiff(large.screen.data$D16$NAME, large.screen.data$D25g$NAME)
# character(0)

all.equal(large.screen.data$D16$SEQ, large.screen.data$D25m$SEQ)
# [1] TRUE
all.equal(large.screen.data$D16$SEQ, large.screen.data$D25p$SEQ)
# [1] TRUE
all.equal(large.screen.data$D16$SEQ, large.screen.data$D25g$SEQ)
# [1] "Lengths (540, 545) differ (string compare on first 540)"
setdiff(large.screen.data$D16$SEQ, large.screen.data$D25g$SEQ)
# character(0)
```

Run median normalization and plot Pearson correlation.

```{r fig-1b-2}
normalize.1b = list(
  D16=data.frame(NAME=large.screen.data$D16$NAME, D16=large.screen.data$D16[, 7]),
  D25m=data.frame(NAME=large.screen.data$D25m$NAME, D25m=large.screen.data$D25m[, 7]),
  D25p=data.frame(NAME=large.screen.data$D25p$NAME, D25p=large.screen.data$D25p[, 7]),
  D25g=data.frame(NAME=large.screen.data$D25g$NAME, D25g=large.screen.data$D25g[, 7])
)

library(DESeq2)

prenormalized.1b.df = merge(normalize.1b$D16, normalize.1b$D25m, by="NAME")
prenormalized.1b.df = merge(prenormalized.1b.df, normalize.1b$D25p, by="NAME")
prenormalized.1b.df = merge(prenormalized.1b.df, normalize.1b$D25g, by="NAME")

myColData = DataFrame(row.names=names(normalize.1b), condition=factor(names(normalize.1b)))
DESeq2.1b = DESeqDataSetFromMatrix(data.frame(row.names=prenormalized.1b.df$NAME, prenormalized.1b.df[, -1]), colData=myColData, design= ~ condition)

DESeq2.1b %<>% estimateSizeFactors
print(sizeFactors(DESeq2.1b))
#       D16      D25m      D25p      D25g 
# 1.4526185 1.0194892 0.9030923 0.7457682

correlation.1b = cor(counts(DESeq2.1b, normalized=T), method="pearson")
correlation.1b %>% round(2) %>% print
#       D16 D25m D25p D25g
# D16  1.00 1.00 0.99 0.95
# D25m 1.00 1.00 0.99 0.95
# D25p 0.99 0.99 1.00 0.97
# D25g 0.95 0.95 0.97 1.00

pheatmap(correlation.1b, cluster_rows=F, cluster_cols=F, border_color="black",
  color=colorRampPalette(c("white", "grey45"))(100), breaks=seq(0.90, 1.00, length.out=100),
  display_numbers=round(correlation.1b, 2), fontsize_number=10
)
```

Figure 1C

```{r load-1c-data-1, echo=F}
volcano.input = list(
  fread("internal-data/First_Large_pool_Day16_NoDox_July2018_vs_Day25_NoDox_July2018_All.txt"),
  fread("internal-data/First_Large_pool_Day16_NoDox_July2018_vs_Day25_PlusDox_July2018_All.txt"),
  fread("internal-data/First_Large_pool_Day25_NoDox_July2018_vs_Day25_PlusDox_July2018_All.txt"),
  fread("internal-data/First_Large_pool_Day25_PlusDox_July2018_vs_Day25_PlusGRAFT_All.txt")
)
```

```{r fig-1c}
# volcano.input = list(
#   fread("1c.1.txt"),
#   fread("1c.2.txt"),
#   fread("1c.3.txt"),
#   fread("1c.4.txt")
# )

for (j in 1:length(volcano.input)) {
  plot(-log10(PValue) ~ logFC, data=volcano.input[[j]], pch=20, cex=0.70,
    col=ifelse(volcano.input[[j]]$PValue <= 1e-5, "black", "grey50"),
    xlim=c(-1.0, +1.5), ylim=c(0, 20),
    xlab=expression("log"[2] * " (fold change)"), ylab=expression("-log"[10] * " (p-value)"),
    yaxt="n"
  )
  axis(side=2, at=seq(0, 20, by=5), las=2)
  abline(h=5.0, col="grey80", lty=2)
  if (j == 1) {
  }
  if (j == 2 | j == 3) {
    text.show = volcano.input[[j]][grep("^BCL2L1_", volcano.input[[j]]$sgRNA), ]
    text(x=text.show$logFC, y=-log10(text.show$PValue) + 1.0, labels=paste0("sg", text.show$sgRNA))
    points(text.show$logFC, -log10(text.show$PValue), pch=20, cex=1.10, col="red")
  }
  if (j == 4) {
    text.show = volcano.input[[j]][grep("^TP53_", volcano.input[[j]]$sgRNA), ]
    text(x=text.show$logFC, y=-log10(text.show$PValue) + 1.0, labels=paste0("sg", text.show$sgRNA))
    points(text.show$logFC, -log10(text.show$PValue), pch=20, cex=1.10, col="blue")
  }
}
```

Figure 1E

```{r load-1e-data-1, echo=F}
heatmap.input = list(
  read.xlsx("internal-data/220929 small pool gRNA raw and processed figures.xlsx", sheet=1),
  read.xlsx("internal-data/220929 small pool gRNA raw and processed figures.xlsx", sheet=2),
  read.xlsx("internal-data/220929 small pool gRNA raw and processed figures.xlsx", sheet=3),
  read.xlsx("internal-data/220929 small pool gRNA raw and processed figures.xlsx", sheet=4),
  read.xlsx("internal-data/220929 small pool gRNA raw and processed figures.xlsx", sheet=6),
  read.xlsx("internal-data/220929 small pool gRNA raw and processed figures.xlsx", sheet=5)
)
```

```{r fig-1e-1}
# heatmap.input = list(
#   D16=fread("1e.1.txt"),
#   D25m=fread("1e.2.txt"),
#   D25p=fread("1e.3.txt"),
#   D25g=fread("1e.4.txt"),
#   Graft1FC=fread("1f.5.txt"),
#   Graft2FC=fread("1f.6.txt"),
# )

heatmap.pre.cor = list(
  "D16"=data.frame(NAME=heatmap.input[[1]]$NAME, D16=heatmap.input[[1]][, 5]),
  "D25m"=data.frame(NAME=heatmap.input[[2]]$NAME, D25m=heatmap.input[[2]][, 5]),
  "D25p"=data.frame(NAME=heatmap.input[[3]]$NAME, D25p=heatmap.input[[3]][, 4]),
  "D25g"=data.frame(NAME=heatmap.input[[4]]$NAME, D25g=heatmap.input[[4]][, 5])
)

heatmap.merged.cor = Reduce(function(a, b) merge(a, b, by="NAME"), heatmap.pre.cor)
heatmap.merged.cor = heatmap.merged.cor[!grepl("CASP9_3", heatmap.merged.cor$NAME), ]

library(DESeq2)

myColData = DataFrame(row.names=names(heatmap.pre.cor), condition=factor(names(heatmap.pre.cor)))
DESeq2.1e = DESeqDataSetFromMatrix(data.frame(row.names=heatmap.merged.cor$NAME, heatmap.merged.cor[, -1]), colData=myColData, design= ~ condition)

DESeq2.1e %<>% estimateSizeFactors
print(sizeFactors(DESeq2.1e))
#       D16      D25m      D25p      D25g 
# 1.0952949 0.9312472 1.1495497 0.8470177

correlation.1e = cor(counts(DESeq2.1e, normalized=T), method="pearson")
correlation.1e %>% round(2) %>% print
#       D16 D25m D25p D25g
# D16  1.00 1.00 0.99 0.87
# D25m 1.00 1.00 0.99 0.87
# D25p 0.99 0.99 1.00 0.90
# D25g 0.87 0.87 0.90 1.00

pheatmap(correlation.1e, cluster_rows=F, cluster_cols=F, border_color="black",
  color=colorRampPalette(c("white", "grey45"))(100), breaks=seq(min(correlation.1e), max(correlation.1e), length.out=100),
  display_numbers=round(correlation.1e, 2), fontsize_number=10
)
```

Figure 1F

```{r load-1f-data-1}
# heatmap.input = heatmap.input # from figure 1e
# normalized count from DESeq2.1e is used here too.

heatmap.1f.left.1 = counts(DESeq2.1e, normalized=T)
heatmap.1f.left.2 = cbind(
  heatmap.1f.left.1[, 2] / heatmap.1f.left.1[, 1],
  heatmap.1f.left.1[, 3] / heatmap.1f.left.1[, 1],
  heatmap.1f.left.1[, 3] / heatmap.1f.left.1[, 2]
) %>% log2

heatmap.1f.right.1 = Reduce(function(a, b) merge(a, b, by="NAME"), heatmap.input[5:6])
heatmap.1f.right.2 = data.frame(
  row.names=heatmap.1f.right.1[, 1],
  "Small.pool.1"=heatmap.1f.right.1[, 2],
  "Small.pool.2"=heatmap.1f.right.1[, 6]
) %>% log2
```

Order the genes by the averaged fold change order of the right panel. In each gene, sgRNAs will be ordered alphabetically.

```{r fig-1f}
heatmap.1f.right.2$gene = gsub("_.*", "", rownames(heatmap.1f.right.2))
heatmap.1f.right.2$gene[grep("SafeHarbor", heatmap.1f.right.2$gene)] = "SafeHarbor"

heatmap.1f.right.2[grep("SafeHarbor", rownames(heatmap.1f.right.2)), 1:2] %>% rowSums
# SafeHarborchr11_38   SafeHarborchr4_9  SafeHarborchr9_18 
#          0.1588251         -0.3313128         -0.2430640
grep("SafeHarbor", rownames(heatmap.1f.right.2), value=T)[
  heatmap.1f.right.2[grep("SafeHarbor", rownames(heatmap.1f.right.2)), 1:2] %>% rowSums %>% order(decreasing=F)
]
# [1] "SafeHarborchr4_9"   "SafeHarborchr9_18"  "SafeHarborchr11_38"

order.intermediate.1 = aggregate(. ~ gene, data=heatmap.1f.right.2, FUN=function(a) sum(a, na.rm=T))
order.intermediate.2 = order.intermediate.1$gene[order.intermediate.1[, -1] %>% rowSums %>% order(decreasing=F)]
order.intermediate.2
#  [1] "SafeHarbor"                       "TLR4"                            
#  [3] "BCL2L11"                          "CASP9"                           
#  [5] "SLC7A11"                          "CASP2"                           
#  [7] "IL18"                             "NonTargetingControlGuideForHuman"
#  [9] "TNFRSF11B"                        "BBC3"                            
# [11] "TP53"

row.order = paste0(rep(order.intermediate.2, each=3), "_", 1:3)
row.order[1:3] = c("SafeH_chr4_9", "SafeH_chr9_18", "SafeH_chr11_38")
row.order[22:24] = paste0("NTC", "_", 1:3)
# CASP9_3 showed all zero counts. Removing this row.
row.order = row.order[-grep("CASP9_3", row.order)]
row.order
#  [1] "SafeH_chr4_9"   "SafeH_chr9_18"  "SafeH_chr11_38" "TLR4_1"         "TLR4_2"        
#  [6] "TLR4_3"         "BCL2L11_1"      "BCL2L11_2"      "BCL2L11_3"      "CASP9_1"       
# [11] "CASP9_2"        "SLC7A11_1"      "SLC7A11_2"      "SLC7A11_3"      "CASP2_1"       
# [16] "CASP2_2"        "CASP2_3"        "IL18_1"         "IL18_2"         "IL18_3"        
# [21] "NTC_1"          "NTC_2"          "NTC_3"          "TNFRSF11B_1"    "TNFRSF11B_2"   
# [26] "TNFRSF11B_3"    "BBC3_1"         "BBC3_2"         "BBC3_3"         "TP53_1"        
# [31] "TP53_2"         "TP53_3"

# Remove CASP9_3 row
# Set the names of nontargeting controls the same
# Order
heatmap.1f.left.3 = heatmap.1f.left.2[!grepl("CASP9_3", rownames(heatmap.1f.left.2)), ]
rownames(heatmap.1f.left.3)[grep("NonTargetingControl", rownames(heatmap.1f.left.3))] = paste0("NTC_", 1:3)
rownames(heatmap.1f.left.3)[grep("SafeHarbor", rownames(heatmap.1f.left.3))] = paste0("SafeH_", c("chr11_38", "chr4_9", "chr9_18"))
heatmap.1f.left.3 = heatmap.1f.left.3[row.order, ]

heatmap.1f.right.3 = heatmap.1f.right.2[!grepl("CASP9_3", rownames(heatmap.1f.right.2)), ]
rownames(heatmap.1f.right.3)[grep("NonTargetingControl", rownames(heatmap.1f.right.3))] = paste0("NTC_", 1:3)
rownames(heatmap.1f.right.3)[grep("SafeHarbor", rownames(heatmap.1f.right.3))] = paste0("SafeH_", c("chr11_38", "chr4_9", "chr9_18"))
heatmap.1f.right.3 = heatmap.1f.right.3[row.order, ]

pheatmap(heatmap.1f.left.3, cluster_rows=F, cluster_cols=F, border_color=NA,
  show_rownames=T, show_colnames=F,
  color=colorRampPalette(c("blue", "white", "red"))(100), breaks=seq(-0.30, +0.30, length.out=100)
)
pheatmap(heatmap.1f.right.3[, 1:2], cluster_rows=F, cluster_cols=F, border_color=NA,
  show_rownames=T, show_colnames=F,
  color=colorRampPalette(c("blue", "white", "red"))(100), breaks=seq(-0.30, +0.30, length.out=100)
)
```
